"""LLM clinical-narrative generator (grounded, guardrailed)."""

from __future__ import annotations

import json
import re

from pydantic import BaseModel, Field

from app.core.logging import get_logger
from app.services.ai import get_ai_service

log = get_logger("report.narrator")

PROMPT_VERSION = "report-v1"

DISCLAIMER = (
    "This report is generated by an AI decision-support tool for educational and "
    "screening purposes only. It is not a medical diagnosis and is not a substitute for "
    "evaluation by a qualified healthcare professional. Do not start, stop, or change any "
    "treatment based on this report. If you have urgent symptoms, seek medical care immediately."
)

_SYSTEM = (
    "You are a clinical documentation assistant for a medical screening platform. You are given "
    "the STRUCTURED output of a specialist AI model (a condition label, confidence, and severity). "
    "Write clear, calibrated, patient-friendly EDUCATIONAL content that explains the finding. "
    "Rules: (1) Never state a definitive diagnosis — frame as screening/support. (2) Never "
    "prescribe; treatment information must be general and educational. (3) Match urgency to "
    "severity. (4) Be concise and professional, suitable for a hospital-grade report. (5) Ground "
    "everything in the provided finding; do not invent unrelated conditions."
)


class ReportNarrative(BaseModel):
    summary: str = ""
    explanation: str = ""
    causes: list[str] = Field(default_factory=list)
    risk_factors: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    treatment_info: str = ""  # general, educational
    lifestyle: list[str] = Field(default_factory=list)
    follow_up: str = ""
    urgency: str = "routine"  # routine | soon | urgent
    when_to_seek_care: str = ""
    disclaimer: str = DISCLAIMER
    generated_by: str = "template"


def _prompt(context: dict) -> str:
    return (
        "Structured finding (from a specialist model):\n"
        f"{json.dumps(context, indent=2)}\n\n"
        "Respond with ONLY a JSON object (no code fences) with this schema:\n"
        "{\n"
        '  "summary": one-sentence clinical summary,\n'
        '  "explanation": 2-4 sentence educational explanation of the finding,\n'
        '  "causes": [common causes],\n'
        '  "risk_factors": [risk factors],\n'
        '  "recommendations": [clear next steps for the patient],\n'
        '  "treatment_info": general educational treatment overview (NOT a prescription),\n'
        '  "lifestyle": [lifestyle suggestions],\n'
        '  "follow_up": follow-up guidance,\n'
        '  "urgency": "routine" | "soon" | "urgent",\n'
        '  "when_to_seek_care": when to seek professional/urgent care\n'
        "}"
    )


def _extract_json(text: str) -> dict | None:
    text = re.sub(r"^```(?:json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            try:
                return json.loads(m.group(0))
            except json.JSONDecodeError:
                return None
    return None


def _fallback(context: dict) -> ReportNarrative:
    """Deterministic, safe narrative when the LLM is unavailable (mock/offline)."""
    label = context.get("finding", "the finding")
    severity = context.get("severity", "none")
    urgency = {"severe": "urgent", "moderate": "soon"}.get(severity, "routine")
    return ReportNarrative(
        summary=f"Screening identified: {label} (severity: {severity}).",
        explanation=(
            f"The specialist model flagged {label}. This is an automated screening result and "
            "should be confirmed by a clinician."
        ),
        recommendations=[
            "Review these findings with a qualified healthcare professional.",
            "Bring this report to your appointment.",
        ],
        treatment_info=(
            "General management depends on clinical confirmation. Treatment options are best "
            "discussed with a specialist."
        ),
        follow_up="Arrange a follow-up consultation for confirmation and management.",
        urgency=urgency,
        when_to_seek_care="Seek prompt care if symptoms worsen or vision changes acutely.",
        generated_by="template",
    )


async def generate_report_narrative(context: dict) -> ReportNarrative:
    """Generate an educational clinical narrative for a structured finding."""
    ai = get_ai_service()
    if ai.provider_name == "mock":
        return _fallback(context)

    try:
        result = await ai.complete(
            _prompt(context),
            system=_SYSTEM,
            temperature=0.3,
            max_tokens=900,
        )
        data = _extract_json(result.text)
        if not data:
            log.warning("report_parse_failed")
            return _fallback(context)
        data.pop("disclaimer", None)  # always use our deterministic disclaimer
        narrative = ReportNarrative(**{**data, "generated_by": result.model})
        return narrative
    except Exception as exc:
        log.warning("report_generation_failed", error=str(exc))
        return _fallback(context)
